### ISSUE TITLE
[iOS] 시뮬레이터상에서 로그인 팝업 빈페이지

### ISSUE THREAD

**Issue by vgb0332** [JeffGuKang/react-native-kakao-login#18]
RN > 0.60, IOS 13 > Xcode 11에서 iphoneX 시뮬레이터 사용중입니다.

xcode / 터미널에서 모두 정상적으로 빌드 되었고, 버튼에 바인딩 후 버튼 클릭 시 로그인 모달 창은 뜨는데, 안에 아이디, 비밀번호 란이 아예 안뜨는데, 전혀 감이 안오네요..

도움이 필요합니다!

<img width="419" alt="KakaoTalk_Photo_2019-09-27-14-21-30" src="https://user-images.githubusercontent.com/23355692/65744096-38426300-e132-11e9-99ec-0a40617e8ba4.png">

**Comment by JeffGuKang** [comment]
@vgb0332 안녕하세요. 답이 늦었습니다. 혹시 예제도 실행해보셨나요?

**Comment by vgb0332** [comment]
네 실행해봤습니다.
Real Device에서 테스트해보았는데, 실 기기(iphone XR)에서는 잘 뜨네요 이상하게..

**Comment by JeffGuKang** [comment]
@vgb0332 그나마? 다행이네요. 저도 시간될때 바로 테스트해보고 업데이트 하겠습니다. 이슈 남겨주셔서 감사합니다.

**Comment by JeffGuKang** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/216363/66806326-3b2ab980-ef62-11e9-910e-bfa2e2c68f9f.png">
XCode 10.3 에서 iPhone X 시뮬레이터 정상 작동 확인하였습니다. 

iOS의 버전이 다르거나  info.plist의 `NSAppTransportSecurity` 문제일수도 있을거 같은데 현재 XCode 업데이트를 하지 못하는 상태라 테스트 가능하신 분이 도와주시면 감사하겠습니다.
