### ISSUE TITLE
login 후 반환받는 데이터의 필드명이 타입스크립트 인터페이스와 상이합니다.

### ISSUE THREAD

**Issue by venzersiz** [JeffGuKang/react-native-kakao-login#27]
export interface KakaoUser {
    id: string
    accessToken: string
    nickname: string | null
    email: string | null
    profileImage: string | null
    profileImageThumbnail: string | null
    ageRange: string | null
    gender: string | null
}
로 되어 있는데

실제 반환 값의 필드 중 nickname이 nickName으로 들어오네요.

**Comment by JeffGuKang** [comment]
@venzersiz  알려주셔서 감사합니다. 수정하도록 하겠습니다.
