### ISSUE TITLE
프로젝트 셋업 및 초기 설정 이미지가 깨져보입니다.

### ISSUE THREAD

**Issue by kosick** [JeffGuKang/react-native-kakao-login#30]
안녕하세요. 좋은 라이브러리 만들어주셔서 감사합니다. 
적용중인데 프로젝트 셋업 초기 설정란에 있는 이미지들이 링크가 사라진 것 같은데 한번 확인 부탁드릴께요.

**Comment by JeffGuKang** [comment]
https://github.com/JeffGuKang/react-native-kakao-login/releases/tag/2.1.0

테스트한 결과 정상 동작 됩니다. 확인 부탁드려요.
