### ISSUE TITLE
안녕하세요 토큰 오류가 뜨는데 해결할 방법이 있을까요?

### ISSUE THREAD

**Issue by smboy86** [JeffGuKang/react-native-kakao-login#4]
`Error: Error: ErrorResult{errorCode=401, errorMessage='Could not refresh access token'`

카카오 로그인(회원가입) 화면은 잘 뜨는데

유저정보 가져오면 위와같이 에러화면에 뜹니다.

해결방법좀 알려주세요 ~

**Comment by JeffGuKang** [comment]
@smboy86  샘플을 돌려보신건가요? 
`https://developers.kakao.com/apps` 에서 앱 설정을 하시고 키값을 입력하신게 맞으신지요?

**Comment by smboy86** [comment]
> @smboy86 샘플을 돌려보신건가요?
> `https://developers.kakao.com/apps` 에서 앱 설정을 하시고 키값을 입력하신게 맞으신지요?

네 물론이죠 
전부 다 했는거 같은데 초보라 자신이 없지만
일단 셋팅을 안하면 위와 같은 오류가 안나오는데
다 하고 나면 토큰 만료 오류가 보여서요
셋팅을 다시 한번 확인해보겠습니다. (안드로이드만 셋팅했습니다)

**Comment by JeffGuKang** [comment]
@smboy86 
샘플에서 위 에러가 나는거면 셋팅 문제일 가능성이 높습니다. 확인해보시고 결과공유 부탁드려요. 감사합니다.
