### ISSUE TITLE
KakaoWebViewActivity 추가 관련 

### ISSUE THREAD

**Issue by heyman333** [JeffGuKang/react-native-kakao-login#5]
안녕하세요
```
        <activity
            android:name="com.kakao.auth.authorization.authcode.KakaoWebViewActivity"
            android:launchMode="singleTop"
            android:windowSoftInputMode="adjustResize">
        </activity>
```
내용이 모듈안에 포함되어있어 프로젝트 메니페스트에는 추가 안해도 되는줄 알았더니
안하면 에러가 발생하네요

`/com.kakao.auth.authorization.authcode.KakaoWebViewActivity}; have you declared this activity in your AndroidManifest.xml?`

**Comment by JeffGuKang** [comment]
확인해보고 반영하도록 하겠습니다. 
피드백 감사합니다.

**Comment by JeffGuKang** [comment]
@heyman333 현재 예제에서는 문제가 없는 것으로 나옵니다. 추가적인 정보 아시는 분은 알려주세요~.
README에 반영하였습니다.

**Comment by heyman333** [comment]
@JeffGuKang 피드백 감사합니다 👍
