### ISSUE TITLE
iOS에 logout 기능이 빠져 있습니다.

### ISSUE THREAD

**Issue by parksunq** [JeffGuKang/react-native-kakao-login#7]
안드로이드에서 logout이 있는데 iOS의 ReactNativeKakao.m을 보면 logout api가 없습니다.
그래서 react-native에서 logout을 호출하면 에러가 발생합니다.

**Comment by JeffGuKang** [comment]
앗 그런가요. 확인해 보겠습니다. 감사합니다.
