### ISSUE TITLE
android에서 onActivityResult가 카카오에 의해 콜 되지 않은 경우 비정상 종료 발생.

### ISSUE THREAD

**Issue by yjb94** [JeffGuKang/react-native-kakao-login#9]
test case: facebook 로그인을 하려고 할 때, 카카오 Session이 초기화되지 않았기 때문에 IllegalStateException에러 발생.

**Comment by JeffGuKang** [comment]
이슈와 풀리퀘까지 남겨주셔서 감사합니다.
